format_version: 10
pipelines:
  CI-QUESTIONNAIRE:
    group: AT20-israel
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
      ORG_KEY: devops-questionary
      PROJECT_KEY: devops-questionary_devops
    secure_variables:
      SONAR_TOKEN: AES:AjaHZiQZfyh+dmhb0gjLdw==:LaiKZv0CfnJOs2kUjmAS0pLDCs37+WHrVHshLhwaYdokGufj09trnXPcu2Kf+xpy
      DOCKER_PASS: AES:iCyoVdO8W++ukqr0ubxDag==:bIiVhVz8G2rYwLSA1KAoSQ==
    materials:
      git-1def632:
        git: https://github.com/AT20-DevOps/AT20_QUESTIONNAIRE_SERVICE.git
        shallow_clone: false
        auto_update: true
        branch: task-11-israel
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unitest:
            timeout: 0
            resource: 
            - node
            tasks:
            - script: |
                npm install
                npm test
            artifacts:
            - test:
                source: tests/test-results/*.xml
                destination: xml_report
            - build:
                source: tests/test-results/
                destination: html_report
    - Code_inspection:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Sonar_scaner:
            timeout: 15
            resource: 
            - node
            tasks:
            - fetch:
                is_file: false
                source: ./
                stage: test
                job: unitest
                run_if: passed
            - script: |
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
                      -Dsonar.organization=${ORG_KEY} \
                      -Dsonar.projectKey=${PROJECT_KEY} \
                      -Dsonar.sources=. \
                      -Dsonar.host.url=https://sonarcloud.io
    - Package:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker_build:
            timeout: 0
            resources:
            - docker
            tasks:
            - exec:
                arguments:
                - docker build -t at20_questionnaire_service .
                command: echo
                run_if: passed
